# Numpy

In [1]:
import pandas as pd
import numpy as np

In [4]:
#numpy.ndarray-nth dimensional array
type(np.array(['Parag',2,4,5]))

numpy.ndarray

In [5]:
np.array(['Parag',2,4,5])

array(['Parag', '2', '4', '5'], dtype='<U5')

Upcast-as float number will take more value than int so it is upcasted to int

In [6]:
np.array([1,2,3.0])

array([1., 2., 3.])

Two dimensions-list inside a list [[1,2],[3,4]]

In [9]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [10]:
#multi dimension array

In [12]:
np.array([1,2,3],ndmin=5)

array([[[[[1, 2, 3]]]]])

In [13]:
np.array([[1,2],[3,4]],ndmin=6)

array([[[[[[1, 2],
           [3, 4]]]]]])

In [ ]:
#dtype

In [14]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
np.array([2,3,4],dtype=float)

array([2., 3., 4.])

In [17]:
np.array([2.1,3.0,4],dtype=int)

array([2, 3, 4])

In [ ]:
#using different data type

In [21]:
x=np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [24]:
x[0]

(1, 2)

In [25]:
x[1]

(3, 4)

In [23]:
x[0][1]

2

In [26]:
type(x[0][1])

numpy.int64

In [27]:
type(x[0][0])

numpy.int16

Converting an array to matrix-matrix is subclass of array

In [29]:
np.mat(np.array([[1,2],[3,4]]))

matrix([[1, 2],
        [3, 4]])

In [30]:
type(np.mat(np.array([[1,2],[3,4]])))

numpy.matrix

In [31]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

# Numpy.asarray

Convert input into an array

In [36]:
a=[1,2]
b=[[1,2],[6,7]]
type(a)

list

In [37]:
np.asarray(a)
np.asarray(b)

array([[1, 2],
       [6, 7]])

In [33]:
type(np.asarray(a))

numpy.ndarray

Checking

In [38]:
issubclass(np.matrix,np.ndarray)

True

In [40]:
issubclass(np.ndarray,np.matrix)

False

# numpy.asanyarray

it will convert if dataset is available in not a variance of array-see in shudhanshu book

In [43]:
a=[1,2]
type(np.asanyarray(a))
np.asanyarray(a)

array([1, 2])

In [ ]:
a=np.matrix([1,2])


Deep Copy and solo copy

In [44]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [50]:
y=x

In [51]:
y[0]=34546546

In [52]:
y

array([34546546,        2,        3])

In [53]:
x

array([34546546,        2,        3])

In [54]:
x[0]

34546546

In [55]:
x[1]=98

In [56]:
x

array([34546546,       98,        3])

In [57]:
y

array([34546546,       98,        3])

dont want the above situation-
#Deep copy where both variable will point to other places in memory and independent to each other

In [58]:
z=np.copy(x) 

In [59]:
z

array([34546546,       98,        3])

In [60]:
x[0]=1

In [61]:
x

array([ 1, 98,  3])

In [62]:
z

array([34546546,       98,        3])

In [63]:
z[0]=99

In [64]:
z

array([99, 98,  3])

In [65]:
x

array([ 1, 98,  3])

# Numpy.fromfunction

In [ ]:
constructing an array by exe a function over each co-ordinate

In [2]:
np.fromfunction(lambda i,j:i==j,(3,3),dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [3]:
np.fromfunction(lambda i,j:i*j,(3,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [4]:
np.fromfunction(lambda i,j,k:i*j*k,(3,3,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [8]:
np.fromfunction(lambda i,j,k,m:i*j*k*m,(3,3,3,3),dtype=int)

array([[[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  1,  2],
         [ 0,  2,  4]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]],

        [[ 0,  0,  0],
         [ 0,  4,  8],
         [ 0,  8, 16]]]])

In [9]:
np.fromfunction(lambda i,j,k,m:i*j*k*m,(1,3,3,3),dtype=int)

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]]])

In [10]:
np.fromfunction(lambda i,j,k,m:i*j*k*m,(2,3,3,3),dtype=int)

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 1, 2],
         [0, 2, 4]],

        [[0, 0, 0],
         [0, 2, 4],
         [0, 4, 8]]]])

#create a new 1-D array from an iterable object

In [15]:
iterable=(x*x for x in range(5))
iterable

<generator object <genexpr> at 0x00000064A56E5048>

In [16]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

#create a new 1-D array from an string

In [17]:
a=np.fromstring('234 234',sep=' ')
a

array([234., 234.])

In [18]:
type(a)

numpy.ndarray

Create a array from list of array

In [19]:
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])

In [21]:
r=np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [34]:
r[1]

(2, 'dd', 2., 2.)

In [30]:
r[0][1]

'a'

In [31]:
r[1][1]

'dd'

In [32]:
r[2][1]

'xyz'

In [33]:
r[3][1]

'12'

# Data type-Basic operation

In [80]:
my_list=[1,2,3]
mat=np.array(my_list)
print(mat)

[1 2 3]


In [77]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print('Type of this object',type(mat))
print('Here is the ,matrix\n-------\n',mat,'\n-------\n')
print('Dimension of this matrix:',mat.ndim,sep='')
print('Size of this matrix:',mat.size,sep=' ')
print('Shape of this matrix:',mat.shape,sep=' ')
print('Data type of this matrix:',mat.dtype,sep=' ')

Type of this object <class 'numpy.ndarray'>
Here is the ,matrix
-------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
-------

Dimension of this matrix:2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


# Arange and linspace

Arange work for float but range will only work for int

In [46]:
list(range(5,100,5))

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [47]:
list(range(5.5,50,5))

TypeError: 'float' object cannot be interpreted as an integer

In [50]:
list(np.arange(5.5,50,5.5))

[5.5, 11.0, 16.5, 22.0, 27.5, 33.0, 38.5, 44.0, 49.5]

In [52]:
print('21 linearly spaced number between 1 and 5\n----------------------\n')
print((np.linspace(1,5,50)))

21 linearly spaced number between 1 and 5
----------------------

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [54]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

# Matrix Creation

In [55]:
print('Vector of zeroes\n--------------------')
print(np.zeros(5))

Vector of zeroes
--------------------
[0. 0. 0. 0. 0.]


In [56]:
print('matrix of zeroes\n---------------------')
print(np.zeros((3,4)))

matrix of zeroes
---------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [58]:
print('matrix of ones\n---------------------')
print(np.ones((3,4)))

matrix of zeroes
---------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [59]:
print('matrix of zeroes\n---------------------')
print(np.zeros((3,4,2)))

matrix of zeroes
---------------------
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [61]:
print('matrix of ones\n---------------------')
print(np.ones((2,4,2)))

matrix of ones
---------------------
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [63]:
print('matrix of 5s\n---------------------')
print(5+np.ones((3,5)))

matrix of 5s
---------------------
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [64]:
print('matrix of 5s\n---------------------')
print(11+np.ones((3,5)))

matrix of 5s
---------------------
[[12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12.]]


In [65]:
print('matrix of 5s\n---------------------')
print(11*np.ones((3,5)))

matrix of 5s
---------------------
[[11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11.]]


In [66]:
print('Empty matrix\n---------------\n',np.empty((3,5)))  #will copy same previous array

Empty matrix
---------------
 [[11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11.]]


In [67]:
mat1=np.eye(4)
print('Identity matrix of dimension',mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [68]:
mat1=np.eye(2)
print('Identity matrix of dimension',mat1.shape)
print(mat1)

Identity matrix of dimension (2, 2)
[[1. 0.]
 [0. 1.]]


In [69]:
np.arange(3)

array([0, 1, 2])

In [70]:
np.linspace(2.0,3.0,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [71]:
np.logspace(2.0,3.0,num=4,base=10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [ ]:
Example-1
1.3x4x8->zeros +5 *2
2.[4,8,80]
3.convert a list in to mat
4.array(4x5x2)->ones dimension,shape,datatype
5.x1=[3x3x3],x2=[3x3x3]..x1+x2

In [94]:
(np.zeros((3,4,8))+5)*2

array([[[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]]])

In [76]:
np.linspace(4,8,80)

array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
       4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
       4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
       4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
       5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
       5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
       5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
       5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
       6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
       6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
       6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
       6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
       7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
       7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
       7.5443038 , 7.59493671, 7.64556962, 7.69620253, 7.74683

In [93]:
my_list=[[1,2],[3,4]]
np.matrix(my_list)

matrix([[1, 2],
        [3, 4]])

4.array(4x5x2)->ones dimension,shape,datatype

In [92]:
mat=np.ones((4,5,2))
print('dimension:',mat.ndim)
print('Size:',mat.size)
print('Shape:',mat.shape)
print('Dtype',mat.dtype)

dimension: 3
Size: 40
Shape: (4, 5, 2)
Dtype float64


5.x1=[3x3x3],x2=[3x3x3]..x1+x2

In [97]:
x1=np.ones((3,3,3))
x2=np.ones((3,3,3))

In [98]:
x1+x2

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])